if (process.env.NODE_ENV !== 'production') {
  require('dotenv').config();
}

import * as cors from 'cors';

// cors.
var whitelist = [
  'http://localhost:3000',
  'https://mts-tn.vercel.app',
  'https://mts-technonatura.vercel.app',
  'https://dashboard.mts-technonatura.vercel.app',
];
var corsOptions: cors.CorsOptions = {
  origin: function(origin, callback) {
    console.log(process.env.NODE_ENV);
    if (process.env.NODE_ENV !== 'dev') {
      if (origin && whitelist.indexOf(origin) !== -1) {
        callback(null, true);
      } else {
        callback(new Error('Not allowed by CORS'));
      }
    } else {
      callback(null, true);
    }
  },
  credentials: true,
};

export { corsOptions };

/*
{
  npm_config_dry_run: '',
  npm_config_legacy_bundling: '',
  npm_config_save_dev: '',
  MANPATH: '/opt/homebrew/share/man::',
  npm_package_gitHead: '386c9dc556d7685fbb070d8a55f0e8ffaf52c55f',
  npm_config_browser: '',
  npm_config_commit_hooks: 'true',
  npm_config_only: '',
  npm_config_viewer: 'man',
  npm_package_dependencies_mongoose: '^5.12.3',
  npm_config_also: '',
  TERM_PROGRAM: 'vscode',
  npm_config_rollback: 'true',
  npm_config_sign_git_commit: '',
  npm_config_audit: 'true',
  npm_config_usage: '',
  NODE: '/usr/local/bin/node',
  npm_package_devDependencies__types_validator: '^13.1.3',
  npm_package_devDependencies_typescript: '^4.2.4',
  INIT_CWD: '/Users/aldhaneka/Documents/Dev/mts-technonatura-server',
  SHELL: '/bin/zsh',
  TERM: 'xterm-256color',
  npm_config_globalignorefile: '/usr/local/etc/npmignore',
  npm_config_init_author_url: '',
  npm_config_maxsockets: '50',
  npm_config_shell: '/bin/zsh',
  TMPDIR: '/var/folders/_7/kxz7f2cs7f37g9f0j2668t6m0000gn/T/',
  HOMEBREW_REPOSITORY: '/opt/homebrew',
  npm_config_metrics_registry: 'https://registry.npmjs.org/',
  npm_config_parseable: '',
  npm_config_shrinkwrap: 'true',
  npm_config_init_license: 'ISC',
  npm_config_timing: '',
  TERM_PROGRAM_VERSION: '1.55.2',
  npm_config_if_present: '',
  npm_package_scripts_dev: 'nodemon --exec ts-node src/server.ts',
  npm_config_cache_max: 'Infinity',
  npm_config_init_author_email: '',
  npm_config_sign_git_tag: '',
  npm_config_cert: '',
  npm_config_git_tag_version: 'true',
  npm_config_local_address: '',
  npm_config_long: '',
  npm_config_preid: '',
  npm_package_devDependencies__types_jsonwebtoken: '^8.5.1',
  npm_config_fetch_retries: '2',
  npm_config_noproxy: '',
  npm_config_registry: 'https://registry.npmjs.org/',
  ZSH: '/Users/aldhaneka/.oh-my-zsh',
  npm_package_readmeFilename: 'README.md',
  npm_config_key: '',
  npm_config_message: '%s',
  npm_config_versions: '',
  npm_package_description: 'hi there',
  npm_package_license: 'ISC',
  npm_package_devDependencies_dotenv: '^8.2.0',
  npm_config_globalconfig: '/usr/local/etc/npmrc',
  npm_config_always_auth: '',
  npm_config_logs_max: '10',
  npm_config_prefer_online: '',
  SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.DjX1I4NSIr/Listeners',
  npm_package_devDependencies__types_cors: '^2.8.10',
  __CF_USER_TEXT_ENCODING: '0x1F5:0x0:0x2',
  npm_package_devDependencies__types_express: '^4.17.11',
  npm_config_cache_lock_retries: '10',
  npm_config_global_style: '',
  npm_execpath: '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
  PAGER: 'less',
  npm_config_cafile: '',
  npm_config_update_notifier: 'true',
  npm_package_dependencies_cors: '^2.8.5',
  LSCOLORS: 'Gxfxcxdxbxegedabagacad',
  npm_config_audit_level: 'low',
  npm_config_heading: 'npm',
  npm_config_fetch_retry_mintimeout: '10000',
  npm_config_offline: '',
  npm_config_read_only: '',
  npm_config_searchlimit: '20',
  PATH: '/Users/aldhaneka/Documents/Dev/mts-technonatura-server/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/aldhaneka/Documents/Dev/mts-technonatura-server/node_modules/.bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin',
  npm_config_argv: '{"remain":[],"cooked":["run","dev"],"original":["run","dev"]}',
  npm_config_access: '',
  npm_config_json: '',
  npm_config_allow_same_version: '',
  _: '/Users/aldhaneka/Documents/Dev/mts-technonatura-server/node_modules/.bin/ts-node',
  npm_config_description: 'true',
  npm_config_engine_strict: '',
  npm_config_https_proxy: '',
  npm_package_author: '',
  npm_config_init_module: '/Users/aldhaneka/.npm-init.js',
  npm_config_userconfig: '/Users/aldhaneka/.npmrc',
  PWD: '/Users/aldhaneka/Documents/Dev/mts-technonatura-server',
  npm_config_cidr: '',
  npm_config_node_version: '14.15.5',
  npm_config_user: '',
  npm_lifecycle_event: 'dev',
  LANG: 'en_GB.UTF-8',
  npm_package_name: 'mts-technonatura-server',
  npm_config_auth_type: 'legacy',
  npm_config_editor: 'vi',
  npm_config_ignore_prepublish: '',
  npm_config_save: 'true',
  npm_config_script_shell: '',
  npm_config_tag: 'latest',
  npm_package_scripts_start: 'tsc && nodemon dist/server.js',
  npm_package_scripts_build: 'tsc',
  npm_config_before: '',
  npm_config_global: '',
  npm_config_progress: 'true',
  XPC_FLAGS: '0x0',
  npm_config_ham_it_up: '',
  npm_config_optional: 'true',
  npm_config_searchstaleness: '900',
  npm_config_bin_links: 'true',
  npm_config_force: '',
  npm_config_save_prod: '',
  npm_config_searchopts: '',
  npm_package_main: 'server.js',
  npm_config_depth: 'Infinity',
  npm_config_node_gyp: '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
  XPC_SERVICE_NAME: '0',
  npm_package_version: '1.0.0',
  npm_config_rebuild_bundle: 'true',
  npm_config_sso_poll_frequency: '500',
  npm_config_unicode: 'true',
  HOME: '/Users/aldhaneka',
  SHLVL: '3',
  VSCODE_GIT_ASKPASS_MAIN: '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js',
  npm_package_scripts_test: 'echo "Error: no test specified" && exit 1',
  npm_config_fetch_retry_maxtimeout: '60000',
  npm_config_ca: '',
  npm_config_loglevel: 'notice',
  npm_config_save_prefix: '^',
  npm_config_scripts_prepend_node_path: 'warn-only',
  npm_config_sso_type: 'oauth',
  npm_config_strict_ssl: 'true',
  npm_config_tag_version_prefix: 'v',
  HOMEBREW_PREFIX: '/opt/homebrew',
  npm_config_dev: '',
  npm_config_fetch_retry_factor: '10',
  npm_config_group: '20',
  npm_config_save_exact: '',
  npm_package_dependencies_validator: '^13.5.2',
  npm_config_cache_lock_stale: '60000',
  npm_config_prefer_offline: '',
  npm_config_version: '',
  npm_package_devDependencies_ts_node: '^9.1.1',
  npm_config_cache_min: '10',
  npm_config_otp: '',
  LOGNAME: 'aldhaneka',
  LESS: '-R',
  npm_config_cache: '/Users/aldhaneka/.npm',
  npm_config_searchexclude: '',
  npm_config_color: 'true',
  npm_lifecycle_script: 'nodemon --exec ts-node src/server.ts',
  VSCODE_GIT_IPC_HANDLE: '/var/folders/_7/kxz7f2cs7f37g9f0j2668t6m0000gn/T/vscode-git-666d9bb92e.sock',
  npm_config_package_lock: 'true',
  npm_config_proxy: '',
  npm_config_fund: 'true',
  npm_config_package_lock_only: '',
  npm_config_save_optional: '',
  npm_config_user_agent: 'npm/6.14.11 node/v14.15.5 darwin x64',
  npm_config_ignore_scripts: '',
  GIT_ASKPASS: '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh',
  VSCODE_GIT_ASKPASS_NODE: '/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)',
  HOMEBREW_CELLAR: '/opt/homebrew/Cellar',
  INFOPATH: '/opt/homebrew/share/info:',
  npm_package_devDependencies__types_node: '^14.14.37',
  npm_config_cache_lock_wait: '10000',
  npm_package_dependencies_jsonwebtoken: '^8.5.1',
  npm_config_production: '',
  npm_package_dependencies_express: '^4.17.1',
  npm_package_devDependencies__types_bcrypt: '^3.0.1',
  npm_config_save_bundle: '',
  npm_config_send_metrics: '',
  npm_config_init_version: '1.0.0',
  npm_config_node_options: '',
  npm_config_umask: '0022',
  npm_config_scope: '',
  npm_config_git: 'git',
  npm_config_init_author_name: '',
  npm_package_devDependencies_nodemon: '^2.0.7',
  npm_package_devDependencies_ts_node_dev: '^1.1.6',
  npm_config_onload_script: '',
  npm_config_tmp: '/var/folders/_7/kxz7f2cs7f37g9f0j2668t6m0000gn/T',
  npm_config_unsafe_perm: 'true',
  COLORTERM: 'truecolor',
  npm_package_dependencies_bcrypt: '^5.0.1',
  npm_config_format_package_lock: 'true',
  npm_config_link: '',
  npm_config_prefix: '/usr/local',
  npm_node_execpath: '/usr/local/bin/node'
}
*/
